# Visualizing File Changes Across Commits

This notebook analyzes differences in files across multiple tardis-regression-data commits. There are two main approaches to get tardis-regression-data commits:

### Method 1: Run pytest on tardis commits and generate regression commits (False commits)

To fetch tardis commits, you have three options:

- Run pytest on latest n tardis commits
- Run pytest on str or list of multiple tardis commits

### Method 2: Directly use tardis-regression-data repo commits

To get those commits, you have two options:

- Manually provide a list of multiple tardis-regression-data commits
- Get last n tardis-regression-data commits

### Note:
By default this notebook runs pytest on latest n tardis commits and generates falsey regression commits to analyze difference.

In [1]:
from tardisbase.testing.regression_comparison.run_tests import run_tests
from tardisbase.testing.regression_comparison.visualize_files import MultiCommitCompare
from tardisbase.testing.regression_comparison.util import get_last_n_commits
import pandas as pd

INFO:numexpr.utils:Note: detected 192 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
INFO:numexpr.utils:Note: NumExpr detected 192 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 16.
INFO:numexpr.utils:NumExpr defaulting to 16 threads.

Display Configuration

In [2]:
# Configure pandas display options for better visualization
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

Setup Configuration

In [3]:
# Configuration for the analysis
config = {
    "tardis_repo_path": "/home/riddhigangbhoj/tardis-work/tardis",
    "regression_data_repo_path": "/home/riddhigangbhoj/tardis-work/tardis-regression-data",
    "branch": "master",
    # "n": 3, # Last n commits   
    "commits": ["8dc6317d4f2df0d85b33ecebdfe75fde92cf63b8", "511f93cf9739b8e6e3406a97366bae0025438462", "20e253f9a5566ede7eeac4b1322612a547861236","aa91e497724945ca24372ae2e47b3bfbf9be1284"],  # Uncomment for specific commits
    "conda_manager": "conda"
}

## Method 1: Run pytest on tardis commits to generate falsey regression data commits

### Case 1: Test latest N TARDIS commits
Important Note: 
1. Comment out `commits` from config
2. Provide the value of `n` in config
3. To forcely recreate new enviornment each time even when enviornment already exist, do `force_recreate` as `True`
4. Either provide entire "tardis" module or selective path like "tardis/spectrum/tests/test_spectrum_solver.py" in `test_path`
5. Provide path to default current enviornment in `default_curr_env`
6. If you want to use default current enviornment only without creating new enviornment each time, do `use_new_envs` as `False`.

In [4]:
# processed_commits, regression_commits, original_head = run_tests(
#         **config,
#         force_recreate=True,
#         test_path="tardis",
#         default_curr_env="/home/riddhigangbhoj/miniforge3/envs/tardis-master",
#         use_new_envs=True
#     )

### Case 2: Test specific TARDIS commits

Important Note:
1. Comment out `n` from config
2. `commits_input` is list of `commits` hashes from config 
3. If tardis commits provided are [1,2,3,4] then the comparison would be ["2-1","3-2","4-3"] of the respective regression commits. So, make the list accordingly.
4. To forcely recreate new enviornment each time even when enviornment already exist, do `force_recreate` as `True`
5. Either provide entire "tardis" module or selective path like "tardis/spectrum/tests/test_spectrum_solver.py" in `test_path`
6. Provide path to default current enviornment in `default_curr_env`
7. If you want to use default current enviornment only without creating new enviornment each time, do `use_new_envs` as `False`.

In [4]:
processed_commits, regression_commits, original_head = run_tests(
    tardis_repo_path= "/home/riddhigangbhoj/tardis-work/tardis",
    regression_data_repo_path= "/home/riddhigangbhoj/tardis-work/tardis-regression-data",
    branch= "master", 
    commits_input=config["commits"],
    conda_manager=config["conda_manager"],
    force_recreate=True,
    test_path="tardis/spectrum/tests/test_spectrum_solver.py",
    default_curr_env="/home/riddhigangbhoj/miniforge3/envs/tardis-master",
    use_new_envs=True
)

INFO:tardisbase.testing.regression_comparison.run_tests:Original HEAD of regression data repo: 0a4e61da79baf73e5863204b014001a22aae885f
INFO:tardisbase.testing.regression_comparison.run_tests:Processing commit 1/4: 8dc6317d4f2df0d85b33ecebdfe75fde92cf63b8
INFO:tardisbase.testing.regression_comparison.run_tests:Creating conda environment: tardis-test-8dc6317d
INFO:tardisbase.testing.regression_comparison.run_tests:Checking if environment tardis-test-8dc6317d exists...
INFO:tardisbase.testing.regression_comparison.run_tests:Executing command: conda env list
INFO:tardisbase.testing.regression_comparison.run_tests:Command completed successfully. Last 3 lines of output:
INFO:tardisbase.testing.regression_comparison.run_tests:                       * /home/riddhigangbhoj/miniforge3/envs/tardis-master
INFO:tardisbase.testing.regression_comparison.run_tests:                         /home/riddhigangbhoj/miniforge3/envs/tardis-master3
INFO:tardisbase.testing.regression_comparison.run_tests:  base                   /opt/miniconda3
INFO:tardisbase.testing.regression_comparison.run_tests:
INFO:tardisbase.testing.regression_comparison.run_tests:Environment tardis-test-8dc6317d exists, removing it for recreation...
INFO:tardisbase.testing.regression_comparison.run_tests:Executing command: conda env remove --name tardis-test-8dc6317d -y
INFO:tardisbase.testing.regression_comparison.run_tests:Command completed successfully. Last 3 lines of output:
INFO:tardisbase.testing.regression_comparison.run_tests:  Verifying transaction: done
INFO:tardisbase.testing.regression_comparison.run_tests:  Executing transaction: |
INFO:tardisbase.testing.regression_comparison.run_tests:done
INFO:tardisbase.testing.regression_comparison.run_tests:
INFO:tardisbase.testing.regression_comparison.run_tests:Creating conda environment
INFO:tardisbase.testing.regression_comparison.run_tests:Executing command: conda create --name tardis-test-8dc6317d --file /tmp/tmpzk4n0ner.lock -y
INFO:tardisbase.testing.regression_comparison.run_tests:Command completed successfully. Last 3 lines of output:
INFO:tardisbase.testing.regression_comparison.run_tests:  # To deactivate an active environment, use
INFO:tardisbase.testing.regression_comparison.run_tests:  #
INFO:tardisbase.testing.regression_comparison.run_tests:  #     $ conda deactivate
INFO:tardisbase.testing.regression_comparison.run_tests:
INFO:tardisbase.testing.regression_comparison.run_tests:Installing TARDIS with all extras ['viz', 'tardisbase']
INFO:tardisbase.testing.regression_comparison.run_tests:Executing command: conda run -n tardis-test-8dc6317d pip install -e /home/riddhigangbhoj/tardis-work/tardis[viz,tardisbase]
INFO:tardisbase.testing.regression_comparison.run_tests:Command completed successfully. Last 3 lines of output:
INFO:tardisbase.testing.regression_comparison.run_tests:     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [qgridnext]
INFO:tardisbase.testing.regression_comparison.run_tests:
INFO:tardisbase.testing.regression_comparison.run_tests:  Successfully installed lineid_plot-0.6 qgridnext-2.0.4 tardis-2025.7.13 tardisbase-0.1.dev39+ga9cd49b76.d20250825
INFO:tardisbase.testing.regression_comparison.run_tests:
INFO:tardisbase.testing.regression_comparison.run_tests:
=== Phase 1: Running 'not continuum' tests for commit 8dc6317d4f2df0d85b33ecebdfe75fde92cf63b8 ===
INFO:tardisbase.testing.regression_comparison.run_tests:Running not continuum tests: conda run -n tardis-test-8dc6317d python -m pytest tardis/spectrum/tests/test_spectrum_solver.py --tardis-regression-data=/home/riddhigangbhoj/tardis-work/tardis-regression-data --generate-reference --disable-warnings -m not continuum
INFO:tardisbase.testing.regression_comparison.run_tests:
=== Phase 2: Running 'continuum' tests for commit 8dc6317d4f2df0d85b33ecebdfe75fde92cf63b8 ===
INFO:tardisbase.testing.regression_comparison.run_tests:Running continuum tests: conda run -n tardis-test-8dc6317d python -m pytest tardis/spectrum/tests/test_spectrum_solver.py --tardis-regression-data=/home/riddhigangbhoj/tardis-work/tardis-regression-data --generate-reference --disable-warnings -m continuum
WARNING:tardisbase.testing.regression_comparison.run_tests:'continuum' tests had failures for commit 8dc6317d4f2df0d85b33ecebdfe75fde92cf63b8
WARNING:tardisbase.testing.regression_comparison.run_tests:Return code: 5
INFO:tardisbase.testing.regression_comparison.run_tests:Stdout: ============================= test session starts ==============================
platform linux -- Python 3.13.3, pytest-8.4.0, pluggy-1.6.0
rootdir: /home/riddhigangbhoj/tardis-work/tardis
configfile: pyproject.toml
plugins: metadata-3.1.1, html-4.1.1, cov-6.1.1, doctestplus-1.4.0, anyio-4.9.0
collected 4 items / 4 deselected / 0 selected

====================== 4 deselected, 2 warnings in 0.02s =======================
ERROR:tardisbase.testing.regression_comparison.run_tests:Stderr: Packets:

Iterations:

ERROR conda.cli.main_run:execute(127): `conda run python -m pytest tardis/spectrum/tests/test_spectrum_solver.py --tardis-regression-data=/home/riddhigangbhoj/tardis-work/tardis-regression-data --generate-reference --disable-warnings -m continuum` failed. (See above for error)
WARNING:tardisbase.testing.regression_comparison.run_tests:Tests completed with some failures for commit 8dc6317d4f2df0d85b33ecebdfe75fde92cf63b8, but regression data was generated
INFO:tardisbase.testing.regression_comparison.run_tests:Processing commit 2/4: 511f93cf9739b8e6e3406a97366bae0025438462
INFO:tardisbase.testing.regression_comparison.run_tests:Creating conda environment: tardis-test-511f93cf
INFO:tardisbase.testing.regression_comparison.run_tests:Checking if environment tardis-test-511f93cf exists...
INFO:tardisbase.testing.regression_comparison.run_tests:Executing command: conda env list
INFO:tardisbase.testing.regression_comparison.run_tests:Command completed successfully. Last 3 lines of output:
INFO:tardisbase.testing.regression_comparison.run_tests:                       * /home/riddhigangbhoj/miniforge3/envs/tardis-master
INFO:tardisbase.testing.regression_comparison.run_tests:                         /home/riddhigangbhoj/miniforge3/envs/tardis-master3
INFO:tardisbase.testing.regression_comparison.run_tests:  base                   /opt/miniconda3
INFO:tardisbase.testing.regression_comparison.run_tests:
INFO:tardisbase.testing.regression_comparison.run_tests:Environment tardis-test-511f93cf exists, removing it for recreation...
INFO:tardisbase.testing.regression_comparison.run_tests:Executing command: conda env remove --name tardis-test-511f93cf -y
INFO:tardisbase.testing.regression_comparison.run_tests:Command completed successfully. Last 3 lines of output:
INFO:tardisbase.testing.regression_comparison.run_tests:  Verifying transaction: done
INFO:tardisbase.testing.regression_comparison.run_tests:  Executing transaction: |
INFO:tardisbase.testing.regression_comparison.run_tests:done
INFO:tardisbase.testing.regression_comparison.run_tests:
INFO:tardisbase.testing.regression_comparison.run_tests:Creating conda environment
INFO:tardisbase.testing.regression_comparison.run_tests:Executing command: conda create --name tardis-test-511f93cf --file /tmp/tmp1x3u__km.lock -y
INFO:tardisbase.testing.regression_comparison.run_tests:Command completed successfully. Last 3 lines of output:
INFO:tardisbase.testing.regression_comparison.run_tests:  # To deactivate an active environment, use
INFO:tardisbase.testing.regression_comparison.run_tests:  #
INFO:tardisbase.testing.regression_comparison.run_tests:  #     $ conda deactivate
INFO:tardisbase.testing.regression_comparison.run_tests:
INFO:tardisbase.testing.regression_comparison.run_tests:Installing TARDIS with all extras ['viz', 'tardisbase']
INFO:tardisbase.testing.regression_comparison.run_tests:Executing command: conda run -n tardis-test-511f93cf pip install -e /home/riddhigangbhoj/tardis-work/tardis[viz,tardisbase]
INFO:tardisbase.testing.regression_comparison.run_tests:Command completed successfully. Last 3 lines of output:
INFO:tardisbase.testing.regression_comparison.run_tests:     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [qgridnext]
INFO:tardisbase.testing.regression_comparison.run_tests:
INFO:tardisbase.testing.regression_comparison.run_tests:  Successfully installed lineid_plot-0.6 qgridnext-2.0.4 tardis-2025.7.13 tardisbase-0.1.dev39+ga9cd49b76.d20250825
INFO:tardisbase.testing.regression_comparison.run_tests:
INFO:tardisbase.testing.regression_comparison.run_tests:
=== Phase 1: Running 'not continuum' tests for commit 511f93cf9739b8e6e3406a97366bae0025438462 ===
INFO:tardisbase.testing.regression_comparison.run_tests:Running not continuum tests: conda run -n tardis-test-511f93cf python -m pytest tardis/spectrum/tests/test_spectrum_solver.py --tardis-regression-data=/home/riddhigangbhoj/tardis-work/tardis-regression-data --generate-reference --disable-warnings -m not continuum
INFO:tardisbase.testing.regression_comparison.run_tests:
=== Phase 2: Running 'continuum' tests for commit 511f93cf9739b8e6e3406a97366bae0025438462 ===
INFO:tardisbase.testing.regression_comparison.run_tests:Running continuum tests: conda run -n tardis-test-511f93cf python -m pytest tardis/spectrum/tests/test_spectrum_solver.py --tardis-regression-data=/home/riddhigangbhoj/tardis-work/tardis-regression-data --generate-reference --disable-warnings -m continuum
WARNING:tardisbase.testing.regression_comparison.run_tests:'continuum' tests had failures for commit 511f93cf9739b8e6e3406a97366bae0025438462
WARNING:tardisbase.testing.regression_comparison.run_tests:Return code: 5
INFO:tardisbase.testing.regression_comparison.run_tests:Stdout: ============================= test session starts ==============================
platform linux -- Python 3.13.3, pytest-8.4.0, pluggy-1.6.0
rootdir: /home/riddhigangbhoj/tardis-work/tardis
configfile: pyproject.toml
plugins: metadata-3.1.1, anyio-4.9.0, doctestplus-1.4.0, cov-6.1.1, html-4.1.1
collected 4 items / 4 deselected / 0 selected

====================== 4 deselected, 2 warnings in 0.02s =======================
ERROR:tardisbase.testing.regression_comparison.run_tests:Stderr: Packets:

Iterations:

ERROR conda.cli.main_run:execute(127): `conda run python -m pytest tardis/spectrum/tests/test_spectrum_solver.py --tardis-regression-data=/home/riddhigangbhoj/tardis-work/tardis-regression-data --generate-reference --disable-warnings -m continuum` failed. (See above for error)
WARNING:tardisbase.testing.regression_comparison.run_tests:Tests completed with some failures for commit 511f93cf9739b8e6e3406a97366bae0025438462, but regression data was generated
INFO:tardisbase.testing.regression_comparison.run_tests:Processing commit 3/4: 20e253f9a5566ede7eeac4b1322612a547861236
INFO:tardisbase.testing.regression_comparison.run_tests:Creating conda environment: tardis-test-20e253f9
INFO:tardisbase.testing.regression_comparison.run_tests:Checking if environment tardis-test-20e253f9 exists...
INFO:tardisbase.testing.regression_comparison.run_tests:Executing command: conda env list
INFO:tardisbase.testing.regression_comparison.run_tests:Command completed successfully. Last 3 lines of output:
INFO:tardisbase.testing.regression_comparison.run_tests:                       * /home/riddhigangbhoj/miniforge3/envs/tardis-master
INFO:tardisbase.testing.regression_comparison.run_tests:                         /home/riddhigangbhoj/miniforge3/envs/tardis-master3
INFO:tardisbase.testing.regression_comparison.run_tests:  base                   /opt/miniconda3
INFO:tardisbase.testing.regression_comparison.run_tests:
INFO:tardisbase.testing.regression_comparison.run_tests:Environment tardis-test-20e253f9 exists, removing it for recreation...
INFO:tardisbase.testing.regression_comparison.run_tests:Executing command: conda env remove --name tardis-test-20e253f9 -y
INFO:tardisbase.testing.regression_comparison.run_tests:Command completed successfully. Last 3 lines of output:
INFO:tardisbase.testing.regression_comparison.run_tests:  Verifying transaction: done
INFO:tardisbase.testing.regression_comparison.run_tests:  Executing transaction: /
INFO:tardisbase.testing.regression_comparison.run_tests:done
INFO:tardisbase.testing.regression_comparison.run_tests:
INFO:tardisbase.testing.regression_comparison.run_tests:Creating conda environment
INFO:tardisbase.testing.regression_comparison.run_tests:Executing command: conda create --name tardis-test-20e253f9 --file /tmp/tmpbh39q_f6.lock -y
INFO:tardisbase.testing.regression_comparison.run_tests:Command completed successfully. Last 3 lines of output:
INFO:tardisbase.testing.regression_comparison.run_tests:  # To deactivate an active environment, use
INFO:tardisbase.testing.regression_comparison.run_tests:  #
INFO:tardisbase.testing.regression_comparison.run_tests:  #     $ conda deactivate
INFO:tardisbase.testing.regression_comparison.run_tests:
INFO:tardisbase.testing.regression_comparison.run_tests:Installing TARDIS with all extras ['viz', 'tardisbase']
INFO:tardisbase.testing.regression_comparison.run_tests:Executing command: conda run -n tardis-test-20e253f9 pip install -e /home/riddhigangbhoj/tardis-work/tardis[viz,tardisbase]
INFO:tardisbase.testing.regression_comparison.run_tests:Command completed successfully. Last 3 lines of output:
INFO:tardisbase.testing.regression_comparison.run_tests:     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [qgridnext]
INFO:tardisbase.testing.regression_comparison.run_tests:
INFO:tardisbase.testing.regression_comparison.run_tests:  Successfully installed lineid_plot-0.6 qgridnext-2.0.4 tardis-2025.7.21.dev3+g511f93cf9 tardisbase-0.1.dev39+ga9cd49b76.d20250825
INFO:tardisbase.testing.regression_comparison.run_tests:
INFO:tardisbase.testing.regression_comparison.run_tests:
=== Phase 1: Running 'not continuum' tests for commit 20e253f9a5566ede7eeac4b1322612a547861236 ===
INFO:tardisbase.testing.regression_comparison.run_tests:Running not continuum tests: conda run -n tardis-test-20e253f9 python -m pytest tardis/spectrum/tests/test_spectrum_solver.py --tardis-regression-data=/home/riddhigangbhoj/tardis-work/tardis-regression-data --generate-reference --disable-warnings -m not continuum
INFO:tardisbase.testing.regression_comparison.run_tests:
=== Phase 2: Running 'continuum' tests for commit 20e253f9a5566ede7eeac4b1322612a547861236 ===
INFO:tardisbase.testing.regression_comparison.run_tests:Running continuum tests: conda run -n tardis-test-20e253f9 python -m pytest tardis/spectrum/tests/test_spectrum_solver.py --tardis-regression-data=/home/riddhigangbhoj/tardis-work/tardis-regression-data --generate-reference --disable-warnings -m continuum
WARNING:tardisbase.testing.regression_comparison.run_tests:'continuum' tests had failures for commit 20e253f9a5566ede7eeac4b1322612a547861236
WARNING:tardisbase.testing.regression_comparison.run_tests:Return code: 5
INFO:tardisbase.testing.regression_comparison.run_tests:Stdout: ============================= test session starts ==============================
platform linux -- Python 3.13.3, pytest-8.4.0, pluggy-1.6.0
rootdir: /home/riddhigangbhoj/tardis-work/tardis
configfile: pyproject.toml
plugins: cov-6.1.1, metadata-3.1.1, anyio-4.9.0, doctestplus-1.4.0, html-4.1.1
collected 4 items / 4 deselected / 0 selected

====================== 4 deselected, 2 warnings in 0.02s =======================
ERROR:tardisbase.testing.regression_comparison.run_tests:Stderr: Packets:

Iterations:

ERROR conda.cli.main_run:execute(127): `conda run python -m pytest tardis/spectrum/tests/test_spectrum_solver.py --tardis-regression-data=/home/riddhigangbhoj/tardis-work/tardis-regression-data --generate-reference --disable-warnings -m continuum` failed. (See above for error)
WARNING:tardisbase.testing.regression_comparison.run_tests:Tests completed with some failures for commit 20e253f9a5566ede7eeac4b1322612a547861236, but regression data was generated
INFO:tardisbase.testing.regression_comparison.run_tests:Processing commit 4/4: aa91e497724945ca24372ae2e47b3bfbf9be1284
INFO:tardisbase.testing.regression_comparison.run_tests:Creating conda environment: tardis-test-aa91e497
INFO:tardisbase.testing.regression_comparison.run_tests:Checking if environment tardis-test-aa91e497 exists...
INFO:tardisbase.testing.regression_comparison.run_tests:Executing command: conda env list
INFO:tardisbase.testing.regression_comparison.run_tests:Command completed successfully. Last 3 lines of output:
INFO:tardisbase.testing.regression_comparison.run_tests:                       * /home/riddhigangbhoj/miniforge3/envs/tardis-master
INFO:tardisbase.testing.regression_comparison.run_tests:                         /home/riddhigangbhoj/miniforge3/envs/tardis-master3
INFO:tardisbase.testing.regression_comparison.run_tests:  base                   /opt/miniconda3
INFO:tardisbase.testing.regression_comparison.run_tests:
INFO:tardisbase.testing.regression_comparison.run_tests:Environment tardis-test-aa91e497 exists, removing it for recreation...
INFO:tardisbase.testing.regression_comparison.run_tests:Executing command: conda env remove --name tardis-test-aa91e497 -y
INFO:tardisbase.testing.regression_comparison.run_tests:Command completed successfully. Last 3 lines of output:
INFO:tardisbase.testing.regression_comparison.run_tests:  Verifying transaction: done
INFO:tardisbase.testing.regression_comparison.run_tests:  Executing transaction: /
INFO:tardisbase.testing.regression_comparison.run_tests:done
INFO:tardisbase.testing.regression_comparison.run_tests:
INFO:tardisbase.testing.regression_comparison.run_tests:Creating conda environment
INFO:tardisbase.testing.regression_comparison.run_tests:Executing command: conda create --name tardis-test-aa91e497 --file /tmp/tmpu3jmv2w_.lock -y
INFO:tardisbase.testing.regression_comparison.run_tests:Command completed successfully. Last 3 lines of output:
INFO:tardisbase.testing.regression_comparison.run_tests:  # To deactivate an active environment, use
INFO:tardisbase.testing.regression_comparison.run_tests:  #
INFO:tardisbase.testing.regression_comparison.run_tests:  #     $ conda deactivate
INFO:tardisbase.testing.regression_comparison.run_tests:
INFO:tardisbase.testing.regression_comparison.run_tests:Installing TARDIS with all extras ['viz', 'tardisbase']
INFO:tardisbase.testing.regression_comparison.run_tests:Executing command: conda run -n tardis-test-aa91e497 pip install -e /home/riddhigangbhoj/tardis-work/tardis[viz,tardisbase]
INFO:tardisbase.testing.regression_comparison.run_tests:Command completed successfully. Last 3 lines of output:
INFO:tardisbase.testing.regression_comparison.run_tests:     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [qgridnext]
INFO:tardisbase.testing.regression_comparison.run_tests:
INFO:tardisbase.testing.regression_comparison.run_tests:  Successfully installed lineid_plot-0.6 qgridnext-2.0.4 tardis-2025.8.4.dev3+g20e253f9a tardisbase-0.1.dev39+ga9cd49b76.d20250825
INFO:tardisbase.testing.regression_comparison.run_tests:
INFO:tardisbase.testing.regression_comparison.run_tests:
=== Phase 1: Running 'not continuum' tests for commit aa91e497724945ca24372ae2e47b3bfbf9be1284 ===
INFO:tardisbase.testing.regression_comparison.run_tests:Running not continuum tests: conda run -n tardis-test-aa91e497 python -m pytest tardis/spectrum/tests/test_spectrum_solver.py --tardis-regression-data=/home/riddhigangbhoj/tardis-work/tardis-regression-data --generate-reference --disable-warnings -m not continuum
INFO:tardisbase.testing.regression_comparison.run_tests:
=== Phase 2: Running 'continuum' tests for commit aa91e497724945ca24372ae2e47b3bfbf9be1284 ===
INFO:tardisbase.testing.regression_comparison.run_tests:Running continuum tests: conda run -n tardis-test-aa91e497 python -m pytest tardis/spectrum/tests/test_spectrum_solver.py --tardis-regression-data=/home/riddhigangbhoj/tardis-work/tardis-regression-data --generate-reference --disable-warnings -m continuum

## Method 2: Use existing regression data commits

### A.  Manual Commit Selection
Note:
1. No need to run pytest for this.
2. If commits provided are [1,2,3,4] then the comparison would be ["2-1","3-2","4-3"]. So, make the list accordingly.

In [ ]:
# regression_commits = ["66a96a847c873544babb7bf934040c86433a5962",
#                       "d12d869bd2bb2038c9090852ee9ef998959f412d",
#                       "b008a7180440a697ad5b54a9f77b692d4f71b120",
#                       "a2a946a43d710c44bb3b08bcae69359fe13ed032",
#                       "9404dc594563d9457e3ba91fcaa8400cae231801"]

### B.  Automatically fetch the most recent N commits from regression data repository
Note:
1. No need to run pytest for this.
2. Set `n` to the number of recent regression commits you want to fetch.

In [ ]:
# regression_commits = get_last_n_commits(n=2, repo_path=config["regression_data_repo_path"])
# regression_commits

## Visualize File Changes
Create a visualizer object to analyze file changes across commits.
Note:
1. Uncomment and set `file_extensions` to any type of file type to filter specific files.
2. Choose `compare_function` of your choice either "git_diff" or "cmd_diff"
    - 'git_diff': Uses git's built-in diff functionality to compare files
          directly within the repository.
    - 'cmd_diff': Extracts files to temporary locations and uses the
          system's diff command.

#### Case 1: Direct regression data commits (no TARDIS commits)
Use when you are directly providing regression commits.

In [ ]:
# visualizer = MultiCommitCompare(
#     regression_repo_path=config["regression_data_repo_path"],
#     commits=regression_commits,
#     # file_extensions=('.h5', '.hdf5') # Uncomment to filter specific files
#     compare_function="git_diff"
# )

#### Case 2: Regression data commits generated from TARDIS commits
Use when you are providing tardis comits.
Note:
1. These regression commits are falsey commits(created just for testing).

In [5]:
visualizer = MultiCommitCompare(
    regression_repo_path=config["regression_data_repo_path"],
    commits=regression_commits,
    tardis_commits=processed_commits,
    tardis_repo_path=config["tardis_repo_path"],
    # file_extensions=('.h5', '.hdf5') # Uncomment to filter specific files
    compare_function="git_diff"
)

### Analyze the commits

In [6]:
visualizer.analyze_commits()

Analyzing 4 commits (3 transitions)...
Processing transition 1/3: 3c7bc2-87281e
Processing transition 2/3: 7a8bf1-3c7bc2
Processing transition 3/3: 5b41bf-7a8bf1
Found 391 total files across all transitions.

### Display the file change matrix

In [7]:
commit_info, legend, matrix = visualizer.get_analysis_results()

### This displays the description of commits which are used to analyze differences.
Note:
1. The false commits generated from tardis commits uses description of tardis commits with prefix "Regression data for --"
2. Directly provided regression commit uses its description as it is.

In [8]:
commit_info

,Commit #,Regression Hash (first 6 chars),Description (first 60 chars),Date
0,1,87281e,Regression data for --Fix missing hyperlink for the tutorial notebooks in doc (#31,2025-08-18 03:24
1,2,3c7bc2,Regression data for --Return formal integral to `v_inner_solver_workflow.ipynb` (#,2025-08-18 03:47
2,3,7a8bf1,Regression data for --Refactor `make_source_function` into solver (#3177),2025-08-18 04:27
3,4,5b41bf,Regression data for --diataxis (#3219),2025-08-18 04:45

### Display legend

In [9]:
legend

A          Added
D        Deleted
M       Modified
•      Unchanged
−    Not-Present
Name: Legend, dtype: object

### The matrix below shows file changes across commit transitions. 
Each row represents a file, and each column represents a commit transition (e.g., "2cbdea-6483ea" means changes from commit 2cbdea to 6483ea).

In [10]:
matrix

,Files,3c7bc2-87281e,7a8bf1-3c7bc2,5b41bf-7a8bf1
0,.gitattributes,•,•,•
1,.github/actions/setup_env/action.yml,•,•,•
2,.github/workflows/run-notebook.yml,•,•,•
3,.github/workflows/trigger-lfs-cache.yml,•,•,•
4,.gitignore,•,•,•
5,LICENSE,•,•,•
6,__init__.py,•,•,•
7,arepo_data/arepo_snapshot.hdf5,•,•,•
8,arepo_data/arepo_snapshot.json,•,•,•
9,atom_data/chianti_He.h5,•,•,•
10,atom_data/kurucz_atom_chianti_many.h5,•,•,•
11,atom_data/kurucz_cd23_chianti_H_He.h5,•,•,•
12,atom_data/kurucz_cd23_chianti_H_He_latest.h5,•,•,•
13,atom_data/kurucz_cd23_chianti_Si.h5,•,•,•
14,atom_data/new_kurucz_cd23_chianti_H_He.h5,•,•,•
15,atom_data/nlte_atom_data/TestNLTE_He_Ti.h5,•,•,•
16,atom_data/stardis_atom_data/tardis_adata_vald_longlist.hdf,•,•,•
17,atom_data/stardis_atom_data/tardis_adata_vald_shortlist.hdf,•,•,•
18,compare.py,•,•,•
19,compare_regression_data.ipynb,•,•,•
20,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties__direction__.npy,•,•,•
21,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties__energy_cmf__.npy,•,•,•
22,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties__energy_rf__.npy,•,•,•
23,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties__location__.npy,•,•,•
24,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties__nu_cmf__.npy,•,•,•
25,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties__nu_rf__.npy,•,•,•
26,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties__shell__.npy,•,•,•
27,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties__status__.npy,•,•,•
28,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties__time_index__.npy,•,•,•
29,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties__time_start__.npy,•,•,•
30,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties_cumulative_energy__direction__.npy,−,A,•
31,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties_cumulative_energy__energy_cmf__.npy,−,A,•
32,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties_cumulative_energy__energy_rf__.npy,−,A,•
33,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties_cumulative_energy__location__.npy,−,A,•
34,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties_cumulative_energy__nu_cmf__.npy,−,A,•
35,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties_cumulative_energy__nu_rf__.npy,−,A,•
36,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties_cumulative_energy__shell__.npy,−,A,•
37,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties_cumulative_energy__status__.npy,−,A,•
38,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties_cumulative_energy__time_index__.npy,−,A,•
39,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties_cumulative_energy__time_start__.npy,−,A,•
40,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties_legacy_energy__direction__.npy,−,A,•
41,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties_legacy_energy__energy_cmf__.npy,−,A,•
42,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties_legacy_energy__energy_rf__.npy,−,A,•
43,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties_legacy_energy__location__.npy,−,A,•
44,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties_legacy_energy__nu_cmf__.npy,−,A,•
45,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties_legacy_energy__nu_rf__.npy,−,A,•
46,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties_legacy_energy__shell__.npy,−,A,•
47,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties_legacy_energy__status__.npy,−,A,•
48,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties_legacy_energy__time_index__.npy,−,A,•
49,tardis/energy_input/tests/test_gamma_ray_packet_source_minimal/test_gamma_ray_packet_properties_legacy_energy__time_start__.npy,−,A,•
50,tardis/opacities/tests/test_opacity_solver/test_new_macro_atom_solver__downbranch-False__.h5,M,M,M
51,tardis/opacities/tests/test_opacity_solver/test_new_macro_atom_solver__downbranch-True__.h5,M,M,M
52,tardis/opacities/tests/test_opacity_solver/test_new_macro_atom_solver__macroatom-False__.h5,M,M,M
53,tardis/opacities/tests/test_opacity_solver/test_new_macro_atom_solver__macroatom-True__.h5,M,M,M
54,tardis/opacities/tests/test_tau_sobolev/test_calculate_beta_sobolevs.npy,•,•,•
55,tardis/opacities/tests/test_tau_sobolev/test_calculate_sobolev_line_opacity.h5,M,M,M
56,tardis/plasma/equilibrium/tests/test_level_populations/test_level_population_solver/test_solve__collisional_rate_solver0-radiative_transitions0__.h5,M,M,M
57,tardis/plasma/equilibrium/tests/test_rate_matrix/test_rate_matrix_solver__collisional_rate_solver0-radiative_transitions0__.h5,M,M,M
58,tardis/plasma/tests/test_complete_plasmas/test_plasma/TestPlasma.h5,•,•,•
59,tardis/plasma/tests/test_complete_plasmas/test_plasma/plasma_unittest_disable_electron_scattering_False.h5,M,M,M
60,tardis/plasma/tests/test_complete_plasmas/test_plasma/plasma_unittest_disable_electron_scattering_True.h5,M,M,M
61,tardis/plasma/tests/test_complete_plasmas/test_plasma/plasma_unittest_excitation_dilute-lte.h5,M,M,M
62,tardis/plasma/tests/test_complete_plasmas/test_plasma/plasma_unittest_excitation_lte.h5,M,M,M
63,tardis/plasma/tests/test_complete_plasmas/test_plasma/plasma_unittest_helium_treatment_recomb-nlte.h5,M,M,M
64,tardis/plasma/tests/test_complete_plasmas/test_plasma/plasma_unittest_helium_treatment_recomb-nlte_delta_treatment_0.5.h5,M,M,M
65,tardis/plasma/tests/test_complete_plasmas/test_plasma/plasma_unittest_initial_t_inner_10000 K.h5,M,M,M
66,tardis/plasma/tests/test_complete_plasmas/test_plasma/plasma_unittest_initial_t_rad_10000 K.h5,M,M,M
67,tardis/plasma/tests/test_complete_plasmas/test_plasma/plasma_unittest_ionization_lte.h5,M,M,M
68,tardis/plasma/tests/test_complete_plasmas/test_plasma/plasma_unittest_ionization_nebular.h5,M,M,M
69,tardis/plasma/tests/test_complete_plasmas/test_plasma/plasma_unittest_line_interaction_type_downbranch.h5,M,M,M
70,tardis/plasma/tests/test_complete_plasmas/test_plasma/plasma_unittest_line_interaction_type_macroatom.h5,M,M,M
71,tardis/plasma/tests/test_complete_plasmas/test_plasma/plasma_unittest_line_interaction_type_scatter.h5,M,M,M
72,tardis/plasma/tests/test_complete_plasmas/test_plasma/plasma_unittest_nlte.h5,M,M,M
73,tardis/plasma/tests/test_complete_plasmas/test_plasma/plasma_unittest_nlte_classical_nebular.h5,M,M,M
74,tardis/plasma/tests/test_complete_plasmas/test_plasma/plasma_unittest_nlte_coronal_approximation.h5,M,M,M
75,tardis/plasma/tests/test_complete_plasmas/test_plasma/plasma_unittest_radiative_rates_type_blackbody.h5,M,M,M
76,tardis/plasma/tests/test_complete_plasmas/test_plasma/plasma_unittest_radiative_rates_type_detailed.h5,M,M,M
77,tardis/plasma/tests/test_complete_plasmas/test_plasma/plasma_unittest_radiative_rates_type_detailed_w_epsilon_1e-10.h5,M,M,M
78,tardis/plasma/tests/test_complete_plasmas/test_plasma/plasma_unittest_radiative_rates_type_dilute-blackbody.h5,M,M,M
79,tardis/plasma/tests/test_hdf_plasma/test_atomic_data_uuid.txt,•,•,•
80,tardis/plasma/tests/test_hdf_plasma/test_collection__density__.npy,•,•,•
81,tardis/plasma/tests/test_hdf_plasma/test_collection__t_rad__.npy,•,•,•
82,tardis/plasma/tests/test_hdf_plasma/test_collection__w__.npy,•,•,•
83,tardis/plasma/tests/test_hdf_plasma/test_hdf_helium_treatment.txt,•,•,•
84,tardis/plasma/tests/test_hdf_plasma/test_hdf_levels.h5,M,M,M
85,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__abundance__.npy,•,•,•
86,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__atomic_mass__.npy,•,•,•
87,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__beta_rad__.npy,•,•,•
88,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__beta_sobolev__.npy,•,•,•
89,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__density__.npy,•,•,•
90,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__electron_densities__.npy,•,•,•
91,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__excitation_energy__.npy,•,•,•
92,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__f_lu__.npy,•,•,•
93,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__g__.npy,•,•,•
94,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__g_electron__.npy,•,•,•
95,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__general_level_boltzmann_factor__.npy,•,•,•
96,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__ion_number_density__.npy,•,•,•
97,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__ionization_data__.npy,•,•,•
98,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__j_blues__.npy,•,•,•
99,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__level_boltzmann_factor__.npy,•,•,•
100,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__level_number_density__.npy,•,•,•
101,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__lines__.npy,•,•,•
102,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__lines_lower_level_index__.npy,•,•,•
103,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__lines_upper_level_index__.npy,•,•,•
104,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__metastability__.npy,•,•,•
105,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__nu__.npy,•,•,•
106,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__number_density__.npy,•,•,•
107,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__partition_function__.npy,•,•,•
108,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__phi__.npy,•,•,•
109,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__selected_atoms__.npy,•,•,•
110,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__stimulated_emission_factor__.npy,•,•,•
111,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__t_electrons__.npy,•,•,•
112,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__t_rad__.npy,•,•,•
113,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__tau_sobolevs__.npy,•,•,•
114,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__transition_probabilities__.npy,•,•,•
115,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__w__.npy,•,•,•
116,tardis/plasma/tests/test_hdf_plasma/test_hdf_plasma__wavelength_cm__.npy,•,•,•
117,tardis/plasma/tests/test_hdf_plasma/test_hdf_scalars__link_t_rad_t_electron__.npy,•,•,•
118,tardis/plasma/tests/test_hdf_plasma/test_hdf_scalars__time_explosion__.npy,•,•,•
119,tardis/plasma/tests/test_nlte_excitation/test_coll_exc_deexc_matrix__coll_exc_coeff_values0-coll_deexc_coeff_values0-3__.npy,•,•,•
120,tardis/plasma/tests/test_nlte_excitation/test_coll_exc_deexc_matrix__coll_exc_coeff_values1-coll_deexc_coeff_values1-3__.npy,•,•,•
121,tardis/plasma/tests/test_nlte_excitation/test_prepare_bound_bound_rate_matrix.npy,•,•,•
122,tardis/plasma/tests/test_nlte_solver/test_jacobian_matrix.npy,•,•,•
123,tardis/plasma/tests/test_nlte_solver/test_rate_matrix.npy,•,•,•
124,tardis/plasma/tests/test_plasma_continuum/test_exp1_times_exp.npy,•,•,•
125,tardis/plasma/tests/test_tardis_model_density_config/test_electron_densities.npy,•,•,•
126,tardis/plasma/tests/test_tardis_model_density_config/test_isotope_number_densities.h5,M,M,M
127,tardis/plasma/tests/test_tardis_model_density_config/test_t_rad.npy,•,•,•
128,tardis/simulation/tests/test_simulation/test_plasma_estimates__dilution_factor__.h5,M,M,M
129,tardis/simulation/tests/test_simulation/test_plasma_estimates__j_estimator__.h5,M,M,M
130,tardis/simulation/tests/test_simulation/test_plasma_estimates__nu_bar_estimator__.h5,M,M,M
131,tardis/simulation/tests/test_simulation/test_plasma_estimates__output_energies__.h5,M,M,M
132,tardis/simulation/tests/test_simulation/test_plasma_estimates__output_nus__.h5,M,M,M
133,tardis/simulation/tests/test_simulation/test_plasma_estimates__t_radiative__.h5,M,M,M
134,tardis/simulation/tests/test_simulation/test_plasma_state_iterations__iterations_electron_densities__.h5,M,M,M
135,tardis/simulation/tests/test_simulation/test_plasma_state_iterations__iterations_t_inner__.h5,M,M,M
136,tardis/simulation/tests/test_simulation/test_plasma_state_iterations__iterations_t_rad__.h5,M,M,M
137,tardis/simulation/tests/test_simulation/test_plasma_state_iterations__iterations_w__.h5,M,M,M
138,tardis/spectrum/formal_integral/tests/test_source_function/test_Jblue_lu.npy,•,•,•
139,tardis/spectrum/formal_integral/tests/test_source_function/test_Jblue_lu__downbranch__.npy,−,A,•
140,tardis/spectrum/formal_integral/tests/test_source_function/test_Jblue_lu__macroatom__.npy,−,A,•
141,tardis/spectrum/formal_integral/tests/test_source_function/test_Jred_lu.npy,•,•,•
142,tardis/spectrum/formal_integral/tests/test_source_function/test_Jred_lu__downbranch__.npy,−,A,•
143,tardis/spectrum/formal_integral/tests/test_source_function/test_Jred_lu__macroatom__.npy,−,A,•
144,tardis/spectrum/formal_integral/tests/test_source_function/test_att_S_ul.npy,•,•,•
145,tardis/spectrum/formal_integral/tests/test_source_function/test_att_S_ul__downbranch__.npy,−,A,•
146,tardis/spectrum/formal_integral/tests/test_source_function/test_att_S_ul__macroatom__.npy,−,A,•
147,tardis/spectrum/formal_integral/tests/test_source_function/test_e_dot_u.npy,•,•,•
148,tardis/spectrum/formal_integral/tests/test_source_function/test_e_dot_u__downbranch__.h5,−,A,M
149,tardis/spectrum/formal_integral/tests/test_source_function/test_e_dot_u__macroatom__.h5,−,A,M
150,tardis/spectrum/tests/test_spectrum_solver/test_spectrum_solver/TestSpectrumSolver.h5,M,M,M
151,tardis/tests/test_tardis_full/test_transport_simple/TestTransportSimple.h5,M,M,M
152,tardis/tests/test_tardis_full_formal_integral/test_transport_simple_formal_integral/test_j_blue_estimators__-1-downbranch__.npy,•,•,•
153,tardis/tests/test_tardis_full_formal_integral/test_transport_simple_formal_integral/test_j_blue_estimators__-1-macroatom__.npy,•,•,•
154,tardis/tests/test_tardis_full_formal_integral/test_transport_simple_formal_integral/test_j_blue_estimators__30-downbranch__.npy,•,•,•
155,tardis/tests/test_tardis_full_formal_integral/test_transport_simple_formal_integral/test_j_blue_estimators__30-macroatom__.npy,•,•,•
156,tardis/tests/test_tardis_full_formal_integral/test_transport_simple_formal_integral/test_simulation__-1-downbranch__.h5,M,M,M
157,tardis/tests/test_tardis_full_formal_integral/test_transport_simple_formal_integral/test_simulation__-1-macroatom__.h5,M,M,M
158,tardis/tests/test_tardis_full_formal_integral/test_transport_simple_formal_integral/test_simulation__30-downbranch__.h5,M,M,M
159,tardis/tests/test_tardis_full_formal_integral/test_transport_simple_formal_integral/test_simulation__30-macroatom__.h5,M,M,M
160,tardis/tests/test_tardis_full_formal_integral/test_transport_simple_formal_integral/test_spectrum__-1-downbranch__.npy,•,•,•
161,tardis/tests/test_tardis_full_formal_integral/test_transport_simple_formal_integral/test_spectrum__-1-macroatom__.npy,•,•,•
162,tardis/tests/test_tardis_full_formal_integral/test_transport_simple_formal_integral/test_spectrum__30-downbranch__.npy,•,•,•
163,tardis/tests/test_tardis_full_formal_integral/test_transport_simple_formal_integral/test_spectrum__30-macroatom__.npy,•,•,•
164,tardis/tests/test_tardis_full_formal_integral/test_transport_simple_formal_integral/test_spectrum_integrated__-1-downbranch__.npy,•,•,•
165,tardis/tests/test_tardis_full_formal_integral/test_transport_simple_formal_integral/test_spectrum_integrated__-1-macroatom__.npy,•,•,•
166,tardis/tests/test_tardis_full_formal_integral/test_transport_simple_formal_integral/test_spectrum_integrated__30-downbranch__.npy,•,•,•
167,tardis/tests/test_tardis_full_formal_integral/test_transport_simple_formal_integral/test_spectrum_integrated__30-macroatom__.npy,•,•,•
168,tardis/transport/montecarlo/tests/test_continuum/test_montecarlo_continuum.h5,M,M,•
169,tardis/transport/montecarlo/tests/test_montecarlo_main_loop/test_montecarlo_main_loop.h5,M,M,M
170,tardis/transport/montecarlo/tests/test_montecarlo_main_loop/test_montecarlo_main_loop_vpacket_log.h5,M,M,M
171,tardis/transport/montecarlo/tests/test_packet_source/test_black_body_simple_source/test_bb_attributes.h5,M,M,M
172,tardis/transport/montecarlo/tests/test_packet_source/test_black_body_simple_source/test_bb_energies.npy,•,•,•
173,tardis/transport/montecarlo/tests/test_packet_source/test_black_body_simple_source/test_bb_mus.npy,•,•,•
174,tardis/transport/montecarlo/tests/test_packet_source/test_black_body_simple_source/test_bb_nus.npy,•,•,•
175,tardis/transport/montecarlo/tests/test_packet_source/test_black_body_simple_source_rel/test_bb_attributes.h5,M,M,M
176,tardis/transport/montecarlo/tests/test_packet_source/test_black_body_simple_source_rel/test_bb_energies.npy,•,•,•
177,tardis/transport/montecarlo/tests/test_packet_source/test_black_body_simple_source_rel/test_bb_mus.npy,•,•,•
178,tardis/transport/montecarlo/tests/test_packet_source/test_black_body_simple_source_rel/test_bb_nus.npy,•,•,•
179,tardis/transport/montecarlo/tests/test_rpacket_tracker/test_boundary_interactions.npy,•,•,•
180,tardis/transport/montecarlo/tests/test_weighted_packet_source/test_black_body_weighted_source/test_bb_attributes.h5,M,M,M
181,tardis/transport/montecarlo/tests/test_weighted_packet_source/test_black_body_weighted_source/test_bb_energies.npy,•,•,•
182,tardis/transport/montecarlo/tests/test_weighted_packet_source/test_black_body_weighted_source/test_bb_mus.npy,•,•,•
183,tardis/transport/montecarlo/tests/test_weighted_packet_source/test_black_body_weighted_source/test_bb_nus.npy,•,•,•
184,tardis/visualization/tests/test_plot_util/test_plot_util/test_create_wavelength_mask__real__.h5,M,M,M
185,tardis/visualization/tests/test_plot_util/test_plot_util/test_create_wavelength_mask__virtual__.h5,M,M,M
186,tardis/visualization/tools/tests/test_lineid_plotter/test_lineid_plotter__wavelengths0-labels0-top__.png,•,•,•
187,tardis/visualization/tools/tests/test_lineid_plotter/test_lineid_plotter__wavelengths1-labels1-inside__.png,•,•,•
188,tardis/visualization/tools/tests/test_lineid_plotter/test_lineid_plotter__wavelengths2-labels2-along__.png,•,•,•
189,tardis/visualization/tools/tests/test_liv_plot/test_liv_plotter/test_generate_plot_mpl__plotter_generate_plot_mpl0__.h5,M,M,M
190,tardis/visualization/tools/tests/test_liv_plot/test_liv_plotter/test_generate_plot_mpl__plotter_generate_plot_mpl1__.h5,M,M,M
191,tardis/visualization/tools/tests/test_liv_plot/test_liv_plotter/test_generate_plot_mpl__plotter_generate_plot_mpl2__.h5,M,M,M
192,tardis/visualization/tools/tests/test_liv_plot/test_liv_plotter/test_generate_plot_mpl__plotter_generate_plot_mpl3__.h5,M,M,M
193,tardis/visualization/tools/tests/test_liv_plot/test_liv_plotter/test_generate_plot_mpl__plotter_generate_plot_mpl4__.h5,M,M,M
194,tardis/visualization/tools/tests/test_liv_plot/test_liv_plotter/test_generate_plot_mpl__plotter_generate_plot_mpl5__.h5,M,M,M
195,tardis/visualization/tools/tests/test_liv_plot/test_liv_plotter/test_generate_plot_mpl__plotter_generate_plot_mpl6__.h5,M,M,M
196,tardis/visualization/tools/tests/test_liv_plot/test_liv_plotter/test_generate_plot_mpl__plotter_generate_plot_mpl7__.h5,M,M,M

### Cleanup: Reset False Commits
**Warning**: This resets history, proceed with caution.

If you want to clean up false commits generated after running pytest, use `git reset --hard upstream/master`.Here N is the number of false commits generated.